/**
 * Ikuspro 1.0
 *
 * Copyright 2010,
 *
 * Ivan Mosquera Paulo (ivanmosp@gmail.com)
 * Mikel Villamañe Girones (mikel.villamane@ehu.es)
 *
 * Licensed under the GNU General Public License (*)
 *
 * (*) Complete information is provided at license.txt
 *
 **/


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IUAcercaDe.java
 *
 * Created on 13-ago-2009, 11:26:48
 */

package ikuspro.gui;

import ikuspro.interprete.c.Interprete;
import ikuspro.main.ConfiguracionMain;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Locale;
import java.util.ResourceBundle;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Iván Mosquera Paulo
 *
 */
public class IUAcercaDe extends javax.swing.JDialog {
    private static final ResourceBundle mensajes = ResourceBundle.getBundle("ikuspro/gui/Mensajes");

	    private javax.swing.JButton boton;
	    private javax.swing.JEditorPane editorIkuspro;
	    private javax.swing.JEditorPane editorSistema;
	    private javax.swing.JEditorPane editorInterpretes;
	    private javax.swing.JPanel panelBoton;
	    private javax.swing.JPanel panelFoto;
	    private javax.swing.JPanel panelIkuspro;
	    private javax.swing.JPanel panelSistema;
	    private javax.swing.JPanel panelInterpretes;
	    private javax.swing.JScrollPane scrollIkuspro;
	    private javax.swing.JScrollPane scrollSistema;
	    private javax.swing.JScrollPane scrollInterpretes;
	    private javax.swing.JTabbedPane tabPanel;


    /** Creates new form IUAcercaDe */
    public IUAcercaDe(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle(mensajes.getString("Acerca_De_Ikuspro"));
        editorIkuspro.setEditable(false);
        editorSistema.setEditable(false);
        editorInterpretes.setEditable(false);
        setResizable(false);
        centrar();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFoto = new JPanel();
        tabPanel = new javax.swing.JTabbedPane();
        panelIkuspro = new javax.swing.JPanel();
        scrollIkuspro = new javax.swing.JScrollPane();
        editorIkuspro = new javax.swing.JEditorPane();
        editorInterpretes = new javax.swing.JEditorPane();
        panelInterpretes = new javax.swing.JPanel();
        panelSistema = new javax.swing.JPanel();
        scrollSistema = new javax.swing.JScrollPane();
        scrollInterpretes = new javax.swing.JScrollPane();
        editorInterpretes = new javax.swing.JEditorPane();
        editorSistema = new javax.swing.JEditorPane();
        panelBoton = new javax.swing.JPanel();
        boton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout panelFotoLayout = new javax.swing.GroupLayout(panelFoto);
        panelFoto.setLayout(panelFotoLayout);
        JLabel labelFoto = new JLabel(new ImageIcon(getClass().getResource("/splash.png")));
        labelFoto.setMinimumSize(new Dimension(10,10));
        panelFoto.add(labelFoto);
        panelFotoLayout.setHorizontalGroup(
            panelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelFotoLayout.setVerticalGroup(
            panelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelIkuspro.setLayout(new java.awt.BorderLayout());

        editorIkuspro.setContentType("text/html");
        editorIkuspro.setText(getTextoIkuspro());
        scrollIkuspro.setViewportView(editorIkuspro);

        editorInterpretes.setContentType("text/html");
        editorInterpretes.setText(getTextoInterpretes());
        scrollInterpretes.setViewportView(editorInterpretes);
        panelInterpretes.setLayout(new java.awt.BorderLayout());
        panelInterpretes.add(scrollInterpretes, java.awt.BorderLayout.CENTER);

        panelIkuspro.add(scrollIkuspro, java.awt.BorderLayout.CENTER);

        tabPanel.addTab("Ikuspro", panelIkuspro);

        panelSistema.setLayout(new java.awt.BorderLayout());

        editorSistema.setContentType("text/html");
        editorSistema.setText(getTextoSistema());
        scrollSistema.setViewportView(editorSistema);

        panelSistema.add(scrollSistema, java.awt.BorderLayout.CENTER);
        tabPanel.addTab(mensajes.getString("Interprete"), panelInterpretes);
        tabPanel.addTab(mensajes.getString("Sistema"), panelSistema);

        boton.setText(mensajes.getString("Aceptar"));
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });
        panelBoton.add(boton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelFoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(panelBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String getTextoSistema() {
		String mensaje = "";
		mensaje += "<html><body>";
		mensaje += mensajes.getString("Sistema_Operativo:_") + System.getProperty("os.name") + "<br/>";
		mensaje += "Java VM: " + (System.getProperty("java.runtime.version")) + "<br/>";
		mensaje += mensajes.getString("Memoria_utilizada_:_") + ((Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory()) / 1000.0) + " kB <br/>";
		mensaje += "Locale: " + Locale.getDefault();


		return mensaje;
	}

	private String getTextoIkuspro() {
		String mensaje = "";
		mensaje += "<html><body>";
		mensaje += "Ikuspro " + ConfiguracionMain.VERSION + "<br/>";
		mensaje += mensajes.getString("Este_es_un_proyecto_de_Iván_Mosquera_Paulo") + "<br/>";
		mensaje += mensajes.getString("Agradecimientos_a_Mikel_Villamañe_(director_PFC)");
		mensaje += "</body></html>";
		return mensaje;
	}

	private String getTextoInterpretes() {
		String mensaje = "";
		mensaje += mensajes.getString("Interprete_en_uso:_") + "<br/>";
		mensaje += mensajes.getString("Nombre_:_")  + Interprete.NOMBRE + "<br/>";
		mensaje += mensajes.getString("Version_:_") + Interprete.VERSION + "<br/>";
		mensaje += mensajes.getString("Extensiones_:_") + Interprete.EXTENSIONES + "<br/>";
		mensaje += "</body></html>";
		return mensaje;
	}

	private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonActionPerformed

	 private void centrar() {
			Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
			Dimension frameSize = getSize();
			int x = (screenSize.width - frameSize.width) / 2;
			int y = (screenSize.height - frameSize.height) / 2;
			setLocation(x, y);
	}

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IUAcercaDe dialog = new IUAcercaDe(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }



}
